# Generated by Django 2.0.4 on 2018-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180530_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='no_of_copies',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Librarian', 'Librarian'), ('Student', 'Student')], default='Librarian', max_length=7),
        ),
    ]
