# Generated by Django 2.0.4 on 2018-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180530_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='no_of_copies',
            field=models.CharField(max_length=50),
        ),
    ]
