# Generated by Django 2.0.4 on 2018-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180530_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='star_rating',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='books',
            name='no_of_copies',
            field=models.IntegerField(max_length=3),
        ),
    ]
