# Generated by Django 2.0.4 on 2018-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20180721_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested',
            name='no_of_copies',
        ),
        migrations.AlterField(
            model_name='requested',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('toBeReturned', 'To be Returned'), ('Returned', 'Returned')], default='Available', max_length=50),
        ),
    ]
