# Generated by Django 2.0.4 on 2018-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_requested_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
