# Generated by Django 2.0.4 on 2018-07-22 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20180722_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 8, 20, 41, 444174)),
        ),
        migrations.AlterField(
            model_name='requested',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 8, 20, 41, 444150)),
        ),
    ]
