# Generated by Django 2.0.4 on 2018-07-22 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20180722_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 8, 22, 50, 470656)),
        ),
        migrations.AlterField(
            model_name='requested',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 8, 22, 50, 470680)),
        ),
    ]
