# Generated by Django 2.0.4 on 2018-07-28 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20180722_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='issue_date',
            field=models.DateField(default=datetime.date(2018, 7, 28)),
        ),
        migrations.AlterField(
            model_name='requested',
            name='return_date',
            field=models.DateField(default=datetime.date(2018, 7, 28)),
        ),
        migrations.AlterField(
            model_name='requested',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('To Be Returned', 'To be Returned'), ('Returned', 'Returned')], default='Booked', max_length=50),
        ),
    ]
